app:
    build: app
    environment:
        - MENU_FILE="_data/menu.yml"
        - LANDING_FILE="IT-systems/index.md"
        - DOCS_LOCATION="IT-systems"
        - MENU_BASE="/IT-systems/"
        - MENU_BASE_NAME="IT-systems"
        - PLACEHOLDER_START='<div style="display:none" class="generated_start">generated items start</div>'
        - PLACEHOLDER_END='<div style="display:none" class="generated_end">generated items end</div>'
        - PACKAGE_FOLDER_NAME="docs"
        - PACKAGE_GIT_URL="git@github.com:zotya/zotya.github.io.git"
        - REFS_PATH="refs/heads/master"
    volumes:
        - ./.gitconfig:/root/.gitconfig:z
        - ./id_rsa:/root/.ssh/id_rsa:z
